- blocklydemo/src/main/assets/sample_sections/level_3/toolbox.xml
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/ConnectionManager.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/AbstractInputView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockViewFactory.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/InputView.java
- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklylib-core/src/main/java/com/google/blockly/model/Connection.java
- blocklylib-core/src/main/java/com/google/blockly/model/Input.java
- blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/InputView.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/ConnectionManagerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/ConnectionTest.java
This covers most of bug #199 by allowing complex shadow blocks to be added.
However, only connecting shadow blocks to inputs (value and statement) is
supported in this CL. We should review further if we want to support shadows
in a stack of statements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/301)
> Attempt number 3 (or 4?) to make shadow blocks work

- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTest.java
Adding model support for collapsed, deletable, disabled, editable, and movable Block state. Includes I/O.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/310)
> Block state: collapsed, deletable, disabled, editable, and movable

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/Dragger.java
- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTest.java
Last fix for #199 this changes the splicing behavior so that shadow
blocks are replaced instead of bumping the remainder away.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/312)
> Change splice behavior to replace shadows when splicing

- blocklylib-core/src/main/java/com/google/blockly/android/ui/Dragger.java
There was a crash state that could be caused by splicing a block with a
shadow, then recreating the shadow, then triggering a re-layout of the block.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/314)
> Fix to crash caused by shadow splice logic

- blocklylib-core/src/main/java/com/google/blockly/android/ui/Dragger.java
Turns out there's a really common case for deleting non-shadows during a drag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/315)
> Fix a crash when dragging blocks to the trash

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
This prevents the crash in #298. We should still discuss what the desired
behavior for the trash is when loading a workspace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/316)
> Clear trash when loading a workspace

- blocklylib-vertical/src/main/res/layout/default_field_angle.xml
- blocklylib-vertical/src/main/res/layout/default_field_checkbox.xml
- blocklylib-vertical/src/main/res/layout/default_field_color.xml
- blocklylib-vertical/src/main/res/layout/default_field_date.xml
- blocklylib-vertical/src/main/res/layout/default_field_dropdown.xml
- blocklylib-vertical/src/main/res/layout/default_field_input.xml
- blocklylib-vertical/src/main/res/layout/default_field_label.xml
- blocklylib-vertical/src/main/res/layout/default_field_number.xml
- blocklylib-vertical/src/main/res/layout/default_field_variable.xml
- blocklylib-vertical/src/main/res/layout/default_spinner_closed_item.xml
- blocklylib-vertical/src/main/res/layout/default_spinner_dropdown_item.xml
The controller handles recreating the workspace during a restore, but the fields
were also trying to restore and keyed off of the layout id, which is not unique.
This disables the framework restore for these fields so Blockly handles it
correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/321)
> Fix bug #230 by disabling field automatic restore

- blocklylib-core/src/main/java/com/google/blockly/android/ui/VirtualWorkspaceView.java
This hides the crash, though more work is needed to clean up the touch handling
in general. Filed #319 to track multi-touch work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/322)
> Fix bug #288 by suppressing panning pointer crash

- blocklylib-core/src/main/java/com/google/blockly/android/ui/NonPropagatingViewGroup.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/ViewPoint.java
- blocklylib-core/src/main/java/com/google/blockly/model/WorkspacePoint.java
We had one reference to an API 21 call and two parcelable objects missing
CREATOR fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/324)
> Fix lint errors

- blocklylib-core/src/main/java/com/google/blockly/android/ui/Dragger.java
Switch to using the helper coordinate utility to get the touch location on
the screen when we check if a touch is over the trash or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/326)
> Fix #64 Account for zoom when checking if a drop was on the trash

- blocklylib-core/src/main/java/com/google/blockly/android/ToolboxFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockListView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/VirtualWorkspaceView.java
- blocklylib-core/src/main/res/layout/blockly_unified_workspace_contents.xml
First pass on #112. This makes it so a tap on the workspace will close the
toolbox and the trash if either is open. This also updates the toolbox's
measure to wrap the contents of the toolbox.
To do:
-Make opening one close the other.
-Make tapping on the background also close.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/327)
> Make tap on workspace close trash/toolbox

- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/LogAllEventsListener.java
- blocklydemo/src/main/res/menu/dev_actionbar.xml
- blocklydemo/src/main/res/values/strings.xml
- blocklylib-core/src/main/assets/default/test_blocks.json
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyEvent.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/VirtualWorkspaceView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldNumberView.java
- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklylib-core/src/main/java/com/google/blockly/model/Field.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldAngle.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldCheckbox.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldColor.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldDate.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldDropdown.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldImage.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldInput.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldLabel.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldNumber.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldVariable.java
- blocklylib-core/src/main/java/com/google/blockly/model/Input.java
- blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java
- blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlocklyEventTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldDropdownTest.java
Event classes, listener hooks, and one listener implementation. DevTests activity now has a "Log Events" checkbox in it's action bar menu.  Create event works end-to-end.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/335)
> BlocklyEvents (first pass, create events only, foundations of #309)

- blocklylib-core/build.gradle
Code coverage was unnecessarily pulling in jacoco classes into the debug build .aar, causing problems for several users.  This removes code coverage (which was not working properly, anyway), which will eventually be fixed in another build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/341)
> Removing code coverage support from debug builds.

- blocklydemo/src/main/assets/sample_sections/level_3/toolbox.xml
- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
- blocklydemo/src/main/res/menu/dev_actionbar.xml
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/NameVariableDialog.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldVariableView.java
- blocklylib-core/src/main/java/com/google/blockly/model/ToolboxCategory.java
- blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java
- blocklylib-core/src/main/res/layout/blockly_variable_name_dialog.xml
- blocklylib-core/src/main/res/layout/name_variable_view.xml
- blocklylib-core/src/main/res/values/strings.xml
Work on #22. This adds a basic dialog for creating or renaming a variable
and hooks it up to UI elements. Renaming is done through an item in the
variable field's dropdown. Creating is currently a menu item in the
DevTestsActivity.
TODO:
- Add a create variable button to flyouts with the custom="VARIABLE" tag
- Dynamically create getter/setter blocks in VARIABLE flyouts
- Support variable configuration
- Make the variable dialogs prettier
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/350)
> Add basic support for renaming/creating variables

- blocklylib-core/src/main/assets/background_compiler.html
- blocklylib-core/src/main/java/com/google/blockly/android/codegen/CodeGeneratorService.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/BlocklyActivityTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/DraggerTest.java
Fixes bug #219
There were problems sending special characters to the old Android WebView. This adds
some code to escape and unescape the String sent to the generator on older versions.
We should wait to see if any other issues show up on older versions as there may have
been poor testing of encode/decode operations on older versions.
Also adds a couple fixes for running tests on older versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/357)
> Add code to escape the String sent to the generator on older versions

- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldNumberView.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldNumber.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldNumberTest.java
Fixed #348, incorrect field_number precision rendering.
Also, renamed FieldNumber.getValueString() to .getReadableValueString().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/361)
> Fixed #348, incorrect field_number precision rendering.

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/Dragger.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/DraggerTest.java
Also, adding new method .trashRootBlockIgnoringDeletable(..) as a means to override this behavior.
Partial fix for #305.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/368)
> BlocklyController.trashRootBlock(..) now respects the block's deletable flag.

- blocklylib-core/src/main/java/com/google/blockly/model/FieldCheckbox.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTestStrings.java
The JS version of blockly is case sensitive and requires all caps for
true and false values.
See https://github.com/google/blockly/issues/653
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/382)
> Make FieldCheckbox use TRUE/FALSE instead of true/false

- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/SimpleActivity.java
- blocklylib-core/src/main/assets/default/list_blocks.json
- blocklylib-core/src/main/assets/default/logic_blocks.json
- blocklylib-core/src/main/assets/default/loop_blocks.json
- blocklylib-core/src/main/assets/default/math_blocks.json
- blocklylib-core/src/main/assets/default/text_blocks.json
- blocklylib-core/src/main/assets/default/toolbox.xml
- blocklytest/src/androidTest/java/com/google/blockly/android/BlocklyTestActivity.java
Does not include lists_split, because it requires onchange handlers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/384)
> Adding blocks that handle lists, and the text block.

- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/389)
> Fix #388. Ignore parent/prior text nodes.

- blocklylib-core/src/main/java/com/google/blockly/android/ToolboxFragment.java
- blocklylib-core/src/main/java/com/google/blockly/model/ToolboxCategory.java
- blocklylib-core/src/main/res/layout/default_create_variable_button.xml
Work on issue #22. This adds a create variable button to any toolbox
with the custom="VARIABLE" property. It's an ugly button and the
toolbox needs some refactoring to make it easier to lay out and style,
but it works for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/396)
> Rough addition of create variable button

- blocklydemo/src/main/assets/turtle/toolbox_advanced.xml
- blocklylib-core/src/main/assets/default/toolbox.xml
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
By default, start the toolbox closed. Fixes #94. Behavior defined in onLoadInitialWorkspace(), which applications can override.
Also, adding custom="VARIABLE" to Variable categories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/400)
> Start the toolbox closed. Adding custom="VARIABLE"

- blocklylib-core/src/main/java/com/google/blockly/android/ui/CategoryTabs.java
Click handler and view reference were disposed of too soon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/407)
> Fixing Toolbar in #405

- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
- blocklydemo/src/main/res/menu/dev_actionbar.xml
- blocklydemo/src/main/res/values/strings.xml
- blocklylib-core/src/main/java/com/google/blockly/android/WorkspaceFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/VirtualWorkspaceView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/WorkspaceHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/WorkspaceView.java
- blocklylib-core/src/main/res/layout/fragment_workspace.xml
- blocklylib-core/src/main/res/values/attrs.xml
This is configurable at the fragment XML, fragment, object, and VirtualWorkspaceView levels.
Adds a menu item in DevTestsActivity to test this behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/416)
> Adds configuration to support workspaces that are not scrollable

- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
- blocklylib-core/src/main/res/layout/drawers_and_action_bar.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/429)
> Fixing call to onCreateOptionsMenu when scrolling checkbox not found.

- blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlockTypeFieldName.java
- blocklylib-core/src/main/java/com/google/blockly/model/Field.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldDropdown.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/fieldview/BasicFieldDropdownViewTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldDropdownTest.java
Adds central management of available dropdown options. Each `FieldDropdown` stores a reference to an `Options` set, which is effectively an observable list of `FieldDropdown.Option` instances.
The set of options for known block types (i.e., loaded via JSON) can be updated via the new methods `BlockFactory.updateDropDownOptions(blockType, fieldName, newOptions)`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/431)
> Dynamic dropdown options

- blocklydemo/src/main/AndroidManifest.xml
- blocklydemo/src/main/assets/simple_playground_toolbox.xml
- blocklydemo/src/main/java/com/google/blockly/android/demo/AlwaysOpenToolboxActivity.java
- blocklydemo/src/main/res/layout/always_open_toolbox.xml
- blocklydemo/src/main/res/values/strings.xml
- blocklylib-core/src/main/java/com/google/blockly/android/ToolboxFragment.java
Specifically, showing a toolbox on top that is always open.
Fixing a bug in configuration of BlockList block spacing when no tabs are present.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/440)
> Adding a demo for alternative configuration of the Blockly fragments.

- blocklydemo/src/main/AndroidManifest.xml
- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
- blocklydemo/src/main/res/menu/dev_actionbar.xml
- blocklydemo/src/main/res/values/strings.xml
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/WorkspaceFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/ZoomBehavior.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/VirtualWorkspaceView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/WorkspaceHelper.java
- blocklylib-core/src/main/res/values/attrs.xml
Moving the reference to ZoomBehavior into the WorkspaceHelper.
Adding ZoomBehavior.isFixed().
Configuring recenter button based on ZoomBehavior.
Updating DevTests options menu from ZoomBehavior.
Cleaning up comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/451)
> Tweaks to new ZoomBehavior

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java
- blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/WorkspaceStatsTest.java
Minor refactoring to remove some null checks around some lists (and return empty lists instead of nulls).
There's a change on WorkspaceStats to make `getVariableReferences()` -> `getVariableReference(String)` as that was always how it was being used. You might potentially not want to do that if we're expecting other people to integrate with the WorkspaceStats class (as it would be a breaking change).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/468)
> TIdy up code to remove some nulls (and their checks).

- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/NameVariableDialog.java
- blocklylib-core/src/main/res/layout/name_variable_view.xml
- blocklylib-core/src/main/res/values/strings.xml
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/NameVariableDialogTest.java
The "name variable" popup now contains the old name in the text if it's being renamed.
I've also added tests around the old and new functionality.
I also tweaked the layout of the popup to be a bit less cramped (but happy to revert that file if you don't like the changes).
Screenshot of updated layout included
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/469)
> #432 Include current variable name when renaming a variable.

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
A new public method on `BlocklyController` which allows consumers to move all blocks to the trash (similar to `resetWorkspace` except `resetWorkspace` also clears the trash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/476)
> Create trashAllBlocks public method

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyEvent.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlocklySerializerException.java
- blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java
- blocklytest/src/androidTest/java/com/google/blockly/android/codegen/CodeGeneratorServiceTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTest.java
Rename BlocklyXmlHelper.writeOneBlockToXml() to .writeBlockToXml() (both versions), since it may write multiple blocks grouped together under the same root. Clarified the method comments, too.
BlocklySerializerException now extends IOException.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/484)
> Rename BlocklyXmlHelper.writeOneBlockToXml() to .writeBlockToXml()

- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/clipboard/BlockClipDataHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/clipboard/SingleMimeTypeClipDataHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/AbstractBlockView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockListView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockViewFactory.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/Dragger.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/PendingDrag.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldInputView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldNumberView.java
- blocklylib-core/src/main/res/values/strings.xml
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/DraggerTest.java
New DragShadowBuilder renders the dragged block group to an image during dragging.  This improves drag responsiveness and begins the drag view above all over views, even outside of the workspace.
Also, annotate every block drag attempt with ClipDataDescription. A BlockClipDataHelper allows any view to participate in the drag behavior. In a pending CL, the TrashCan will utilize this, but it offers extension to other views outside the Blockly framework (e.g., a sprite, as in Scratch, for copying a block group between workspaces).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/486)
> Use drag shadows to dragged blocks. Also add ClipDataDescription.

- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockViewFactory.java
Fixes #115.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/497)
> Always use the default translucent dragshadow.

- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/SplitActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/TurtleActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
Replaces DEFAULT_WORKSPACE_FILENAME, which as a static constant, wasn't overridable.
Using different workspace files for the demos (grouped by their shared block definitions).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/512)
> Added getWorkspaceSavePath() to AbstractBlocklyActivity.

- blocklylib-core/src/main/java/com/google/blockly/android/BlockListUI.java
- blocklylib-core/src/main/java/com/google/blockly/android/CategorySelectorUI.java
- blocklylib-core/src/main/java/com/google/blockly/android/FlyoutFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/FlyoutController.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockRecyclerViewHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/FlyoutCallback.java
Also, `BlockListHelper` renamed to `BlockRecyclerViewHelper`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/515)
> Refactor cleanup

- blocklydemo/src/main/res/layout/always_open_toolbox.xml
- blocklydemo/src/main/res/layout/styled_content.xml
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/BlocklyActivityHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/CategorySelectorFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/FlyoutFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/FlyoutController.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockListUI.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/CategorySelectorUI.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/CategoryTabs.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/CategoryView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/DefaultVariableCallback.java
- blocklylib-core/src/main/res/layout/blockly_unified_workspace.xml
* Renaming `blockly_toolbox_flyout` and `blockly_trash_flyout` as `blockly_toolbox_ui` and `blockly_trash_ui`, respectively.
* Moving `BlockListUI`, `CategorySelectorUI`, and `DefaultVariableCallback` to the `.android.ui` package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/518)
> Renaming resource ids. Moving interfaces into .ui

- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/BlocklyActivityHelper.java
- blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/FieldColorView.java
One warning remains in AbstractBlockView (generic type mismatch with BlockViewFactory).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/527)
> Fixing deprecations and other build warnings.

- blocklylib-core/src/main/java/com/google/blockly/android/BlocklyActivityHelper.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/528)
> BlocklyActivityHelper no longer assumes FlyoutFragment.

- blocklylib-core/src/main/java/com/google/blockly/android/codegen/CodeGeneratorManager.java
Fix #535 by creating an unbind call that unbinds from the service
and clears state so we don't end up in a situation that can try to
unbind twice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/538)
> Make unbinding from CodeGeneratorService cleaner

- blocklytest/src/androidTest/java/com/google/blockly/model/BlockFactoryTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlocklyEventTest.java
Sidesteps use of PointF.equals(..) in tests. Fixes #540.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/541)
> Fix #540 test failures on API 16.

- blocklydemo/src/main/java/com/google/blockly/android/demo/SplitActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/BlocklyActivityHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldNumberView.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldNumber.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldNumberTest.java
Solves #231 serialization under locales that use commas (or anything else) as a decimal point.
Also improves input in these Locales, allowing the comma to be rendered and typed in the corresponding views.
Number rendering now includes grouping separators (the comma after thousands in English), although those are stripped during parsing for permissive inputs (and also due to incorrect parsing when included in the NumberFormat).
KNOWN ISSUES:
* Fractional numbers are rendered truncated at three significant digits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/546)
> Improve FieldNumber and FieldNumberView for other languages.

- blocklylib-core/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/553)
> Adding support-v4 library to fix build problem with AppCompatActivity

- blocklylib-core/src/main/java/com/google/blockly/android/clipboard/SingleMimeTypeClipDataHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/WorkspaceHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldInputView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldNumberView.java
* Fix number field view, correcting filter for block drags.
* Unify block drag checks from `BasicFiedNumberView` and `BasicFieldInputView` as `WorkspaceHelper.isBlockDrag(..)`.
* `SimpleMimeTypeClipDataHelper`: Filter out non-block drags before casting `getPendingDrag()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/555)
> Fixes Number field rendering.

- blocklydemo/src/main/res/layout/styled_content.xml
- blocklylib-core/src/main/java/com/google/blockly/android/WorkspaceFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/VirtualWorkspaceView.java
- blocklylib-core/src/main/res/values/attrs.xml
Hi, thanks @RoboErikG for the feedback, makes a lot more sense for it to be on the fragment level. So then, would this commit fix the problem?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/558)
> Issue #551 Make grid configurable from xml/APIs

- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/BlockView.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTest.java
Blocks can now be observed by their view instances. Observations are categorized by `Block.UPDATE_*` bit flags. This will allows changes caused by mutators (or mutation events) to be noticed by the views, so the views will update themselves.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/561)
> Adding Observer / Observable to Block class.

- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlockExtension.java
- blocklylib-core/src/main/java/com/google/blockly/model/Field.java
- blocklylib-core/src/main/java/com/google/blockly/model/Input.java
- blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/BlockView.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/ConnectionManagerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTest.java
reshape() updates the inputs and all connections with potentially new values, potentially changing the shape of the block. This method is designed be called by either the constructor or mutators.
This version has not been fully tested, but works well enough to replace the previous block construction implementation.  All old tests pass, and there is no noticeable different in the UI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/563)
> Adding Block.reshape(). Making Inputs immutable.

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklytest/src/androidTest/java/com/google/blockly/android/BlocklyTestCase.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/DraggerTest.java
Adding `BlocklyController.groupAndFireEvents(..)`, and making `.addPendingEvent(..)` public.
These form the basis of a replacement of the prior event framework, allowing better
support for chaining events, and allowing methods outside of `BlocklyController` to initiate
event groups (e.g., `Block.setPosition(..)`, `Field.setValue(..)`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/566)
> Adding BlocklyController.groupAndFireEvents(..)

- blocklylib-core/src/main/java/com/google/blockly/android/ui/WorkspaceHelper.java
- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklylib-core/src/main/java/com/google/blockly/model/Field.java
- blocklylib-core/src/main/java/com/google/blockly/model/Input.java
- blocklytest/src/androidTest/java/com/google/blockly/android/BlocklyTestCase.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockFactoryTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldTest.java
- blocklytest/src/androidTest/java/com/google/blockly/utils/TestBlockObserver.java
- blocklytest/src/androidTest/java/com/google/blockly/utils/TestEventsCallback.java
- blocklytest/src/androidTest/java/com/google/blockly/utils/TestFieldObserver.java
- blocklytest/src/main/res/raw/test_blocks.json
Also
* Adding TestEventCallback, TestBlockObserver, and TestFieldObserver, implementations that each collect their respect events for testing replacing some prior implementations.
* Fix issue with WorkspaceHelper.getView() in a headless mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/572)
> Adding ChangeEvent support to field changes.

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTest.java
Compare to web's block.setOnChange(..), although this (currently) adds the callback to the controller, listening regardless of whether the block is attached to a workspace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/573)
> Adding Block.setEventCallback(EventCallback)

- blocklydemo/src/main/assets/sample_sections/level_2/toolbox.xml
- blocklydemo/src/main/assets/sample_sections/level_3/toolbox.xml
- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/SimpleActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/TurtleActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/BlocklyActivityHelper.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlockExtension.java
- blocklylib-core/src/main/java/com/google/blockly/model/DefaultBlocks.java
* Adding `DefaultBlocks`, a class to store constants related to the default/playground blocks.
* Adding support for Mutators in the `AbstractBlocklyActivity` and `BlocklyActivityHelper`.
* Minor tweaks to DevTests toolbox (previously, "Some blocks" and "Outputs" were identical, looking like a bug).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/574)
>  Adding DefaultBlocks, constants related to the default/playground blocks

- .travis.yml
- blocklydemo/build.gradle
- blocklylib-core/build.gradle
- blocklylib-vertical/build.gradle
- blocklytest/build.gradle
Add travis config to enable ci test run for blockly-android project. 
travis test run result: https://travis-ci.org/shirletan/blockly-android/builds/230122681
Notes:
1. I need turn off lint check on sub- projects as they're failing now. It's workaround to bypass error to enable CI run.
2. It runs on api 22 with arm based emulator. Currently travis is only support arm based emulator as kvm can not be installed on build vm. 
3. test run averages takes about 20 mins for setup, install emulator, and build and run unit tests. arm emulator is 10x slower than x86 emulator. 
4. i squashed individual commits already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/581)
> initial check for blockly-android travis  build

- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/TurtleActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
It was kind of confusing having a class field called mBlockly that is a helper for setting up and managing the Activity and its Fragments. This renames it to the longer, but clearer mBlocklyActivityHelper.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/582)
> Rename AbstractBlocklyActivity.mBlockly to mBlocklyActivityHelper

- blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/BlockView.java
- blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/InputView.java
Fixes #504. For inline inputs if the inputs didn't go to the end
of the line there would be an emtpy rectangle after them. This checks
if there's empty space after the last input on a line and fills it in.
Also simplifies the check if a location is within a block.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/583)
> Fill in block background to end of line

- blocklylib-core/src/main/assets/default/logic_blocks.json
- blocklylib-core/src/main/java/com/google/blockly/android/ui/AbstractBlockView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockViewFactory.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/Dragger.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/mutator/IfElseMutatorFragment.java
- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklylib-core/src/main/java/com/google/blockly/model/mutator/IfElseMutator.java
- blocklylib-core/src/main/java/com/google/blockly/model/mutator/MathIsDivisibleByMutator.java
- blocklylib-core/src/main/res/values/strings.xml
- blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/BlockView.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/AbstractBlockViewTest.java
Implements support for the `Block.reshape(..)` changes. This crude implementation rebuilds the view from the model, and replaces the original view in the view tree. It looses some minor UI state, like highlight and text selection. Be careful of direct references to BlockViews.
Enables `controls_if_mutator` and minor fixes to `math_is_divisible_mutator`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/586)
> Implement (crudely) changing the shape of a BlockView

- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/LuaActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/SimpleActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/SplitActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/StylesActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/TurtleActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/flyout/AlwaysOpenToolboxActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/flyout/NoCategoriesToolboxActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
Adds auto saving and auto loading the workspace to the AbstractBlocklyActivity
with hooks to override the file it is saved to or to override the functionality.
All demo apps are updated to use a unique filename for saving and autosaving
and DevTests overrides the autosave/load to prevent replacing the test
workspace that is loaded each time the activity is started.
Fixes #534
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/594)
> Add an autosave feature to AbstractBlocklyActivity

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/model/VariableCategoryFactory.java
Also fixes a bug with deleting the last variable while the flyout is
open on the variables category.
Fixes #500
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/600)
> Fix bug around creating 'item' variable randomly

- blocklylib-core/src/main/assets/default/test_blocks.json
This was causing a crash in DevTests Section 3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/607)
> Fix field name in test_blocks json

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
We had a way to access the model factory but not he view factory. This
is useful for configureMutators() to avoid having to keep an extra
reference to the view factory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/611)
> Add getBlockViewFactory to BlocklyController

- blocklylib-core/src/main/assets/default/toolbox.xml
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/DefaultVariableCallback.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/mutator/ProcedureDefinitionMutatorFragment.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java
- blocklylib-core/src/main/java/com/google/blockly/model/Input.java
- blocklylib-core/src/main/java/com/google/blockly/model/ProcedureCustomCategory.java
- blocklylib-core/src/main/java/com/google/blockly/model/ProcedureInfo.java
- blocklylib-core/src/main/java/com/google/blockly/model/VariableInfo.java
- blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java
- blocklylib-core/src/main/java/com/google/blockly/model/mutator/AbstractProcedureMutator.java
- blocklylib-core/src/main/java/com/google/blockly/model/mutator/ProcedureCallMutator.java
- blocklylib-core/src/main/java/com/google/blockly/model/mutator/ProcedureDefinitionMutator.java
- blocklylib-core/src/main/java/com/google/blockly/model/mutator/ProceduresIfReturnMutator.java
- blocklylib-core/src/main/java/com/google/blockly/utils/SimpleArraySet.java
- blocklylib-core/src/main/res/values/strings.xml
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/NameManagerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/ProcedureManagerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/WorkspaceStatsTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlocklyEventTest.java
* Refactored variable storage in the WorkspaceStats to use a new VariableInfo object.
* Refactored procedure mutators to use a shared ProcedureInfo object for the mutator description.
* Procedure blocks additions and changes now automatically create variables. Both of these produce changes on the ProcedureCustomCategory and VariableCustomCategory, respectively.
* Fail gracefully on autoload.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/615)
> Procedure additions/mutations => Variable updates

- blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java
- blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java
- blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java
Bug where a procedure reference encountered in XML loading before the procedure definition will throw an uncaught error. This fixes the that, with proper reporting, and catches the BlockLoadingException (instead of IllegalStateException).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/618)
> Fixes crash where procedure reference came before the definition

- blocklytest/src/androidTest/java/com/google/blockly/android/BlocklyTestCase.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/NameVariableDialogTest.java
...such as the variable name dialog tests which fail so often (now set to 5x).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/621)
> Allow individual tests to adjust the timeout

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldInputView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldLabelView.java
- blocklylib-core/src/main/java/com/google/blockly/model/DefaultBlocks.java
- blocklylib-core/src/main/java/com/google/blockly/model/ProcedureCustomCategory.java
- blocklylib-core/src/main/java/com/google/blockly/model/mutator/AbstractProcedureMutator.java
- blocklylib-core/src/main/java/com/google/blockly/model/mutator/ProcedureCallMutator.java
- blocklylib-core/src/main/java/com/google/blockly/model/mutator/ProcedureDefinitionMutator.java
- blocklylib-core/src/main/java/com/google/blockly/utils/SimpleArraySet.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/ProcedureManagerTest.java
This is a WIP on functions.
I replaced the two maps with one, in an effort to reduce the number of parallel keys I need to maintain.
Future step is to do the same with the NameManager, making it a map-like structure to ProcedureBlocks or VariableInfo objects. This also centralizes the canonization of names, and reduces the "surface area" of the name synchronization problem seen during procedure rename.
Also, much more ProcedureManager JavaDocs I missed on the last pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/622)
> Merge ProcedureManager mDefinitions and mReferences maps

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlocklyEvent.java
Blocks now have a reference to their workspace id. Did not remove the parameter from DeleteEvent, because the EventWorkspaceId may have already been cleared on the block.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/627)
> Removing Workspace param on event constructors

- blocklylib-core/build.gradle
- blocklylib-core/deploy.gradle
- blocklylib-vertical/build.gradle
- blocklylib-vertical/deploy.gradle
- build.gradle
- deploy.properties
Adding the gradle tasks necessary to deploy binaries .aar and source files to Bintray.
This is a commit to master to release the old build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/631)
> Adding the gradle tasks necessary to deploy binaries

- deploy.properties
Version numbers should not include a leading 'v'. After uploading without this, the codelab can now resolve the dependency.
This is a commit to master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/633)
> Fix Bintray task. No 'v' before version.

- blocklydemo/build.gradle
- blocklylib-core/build.gradle
- blocklylib-vertical/build.gradle
- blocklytest/build.gradle
- build.gradle
Using the new maven repo (described [here](https://developer.android.com/about/versions/oreo/android-8.0-migration.html#uya)) for support libraries `26.0.1`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/638)
> Updating dependencies to 26.0.1

- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockViewFactory.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/Dragger.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldAngleView.java
Newly deprecated in API 26.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/641)
> Replacing deprecated v13 ViewCompat with v4 ViewCompat.

- blocklylib-core/build.gradle
Usage was removed in #641
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/646)
> Removing dependency on support-v13.

- blocklytest/src/main/AndroidManifest.xml
I ran into the error "Didn't find class “android.support.multidex.MultiDexApplication” on path: DexPathList".
Disabling multidex on the test app (which is not used on other apps, either).
If one wanted multidex, the solution is to create a dex keep file list:
https://developer.android.com/studio/build/multidex.html#keep
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/649)
> Disabling multidex on the blocklytest app.

- Codelab/MusicMaker-starter/build.gradle
- Codelab/MusicMaker-starter/src/main/java/com/google/blockly/codelab/EditFragment.java
- Codelab/MusicMaker-starter/src/main/java/com/google/blockly/codelab/MainActivity.java
- Codelab/MusicMaker-starter/src/main/java/com/google/blockly/codelab/MultiFileAudioPlayer.java
- Codelab/MusicMaker-starter/src/main/java/com/google/blockly/codelab/PlaybackFragment.java
- Codelab/MusicMaker-starter/src/main/res/values/strings.xml
- Codelab/MusicMaker-step1-Blockly/build.gradle
- Codelab/MusicMaker-step1-Blockly/src/main/assets/sound_block_generators.js
- Codelab/MusicMaker-step1-Blockly/src/main/assets/sound_blocks.json
- Codelab/MusicMaker-step1-Blockly/src/main/assets/toolbox.xml
- Codelab/MusicMaker-step1-Blockly/src/main/java/com/google/blockly/codelab/BlocklyFragment.java
- Codelab/MusicMaker-step1-Blockly/src/main/java/com/google/blockly/codelab/EditFragment.java
- Codelab/MusicMaker-step1-Blockly/src/main/java/com/google/blockly/codelab/MainActivity.java
- Codelab/MusicMaker-step1-Blockly/src/main/java/com/google/blockly/codelab/MultiFileAudioPlayer.java
- Codelab/MusicMaker-step1-Blockly/src/main/java/com/google/blockly/codelab/PlaybackFragment.java
- Codelab/MusicMaker-step1-Blockly/src/main/res/values/strings.xml
- Codelab/MusicMaker-step1-Blockly/src/main/res/values/styles.xml
- Codelab/build.gradle
* Added button handling in EditFragment.
* Import blockly dependency (and associated Android support files, from maven).
* Adding BlocklyFragment, triggered by selecting one of the buttons on the EditFragment, with MusicMaker specific blocks, toolbox, and generators.
* Added copyrights to source files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/656)
> Adding Codelab step to add Blockly

- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
Adjust the block mutation serialization order to account for JavaScript's in-order XML processing.
Fixes #666
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/668)
> Fix #666: Serialize block with <mutation> before inputs and fields

- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldNumberView.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldNumber.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/fieldview/BasicFieldLabelViewTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/fieldview/BasicFieldNumberViewTest.java
Corrected NumberFormat max fractional digits when no precision is specified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/667)
> Adding tests for BasicFieldNumberView, and fixing #665

- blocklytest/src/androidTest/java/com/google/blockly/android/codegen/CodeGeneratorServiceTest.java
- blocklytest/src/main/AndroidManifest.xml
* Use android.support.multidex.MultiDexApplication, per [this doc](https://developer.android.com/studio/build/multidex.html). Not using this was causing total test failure in API 18 and 19 (various JUnit class not found errors).
* Rewrote `testEscapeFieldDataForAndroidWebView()` for better assertion output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/669)
> Correct Multidex. Better test error output.

- blocklytest/build.gradle
Successfully ran tests on APIs 18, 19, 22, 24, 25, and 26.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/671)
> Import Multidex app in dependencies.

- blocklydemo/src/main/assets/sample_sections/level_3/toolbox.xml
- blocklydemo/src/main/assets/sample_sections/mock_block_definitions.json
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldImageView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/FieldView.java
Adding DevTests block that depends upon images from the network (hosted at github.io).
Adding synchronization in BasicFieldImageView around usages of mImageField. While this means these methods can block the UI thread, the logic and methods within should all be very short lived and should rarely collide.
These do not include a test case, and I have not been able to force the failures reported in #678.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/679)
> Protect against race conditions in BasicFieldImageView

- blocklydemo/src/main/assets/sample_sections/level_3/toolbox.xml
- blocklydemo/src/main/assets/sample_sections/mock_block_definitions.json
- blocklydemo/src/main/assets/sample_sections/mock_block_initial_workspace.xml
- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java
- blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/BlockView.java
- blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/InputView.java
- blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/PatchManager.java
The PatchManager now loads both the default top-left path and the
hat patch into memory, since they can both be in use in the same workspace..
Added a test block to the DevTest toolbox and workspace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/682)
> Adding support from "style" blocks and "hat": "cap"

- blocklydemo/src/main/assets/sample_sections/level_3/toolbox.xml
- blocklydemo/src/main/assets/sample_sections/mock_block_definitions.json
- blocklylib-core/src/main/java/com/google/blockly/utils/ColorUtils.java
Adding demo blocks to test how blocks colors rendered, including blocks with missing or invalid color specifications.
Fix the color alpha issue noted in #686, using suggested fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/689)
> Block color tests

- blocklylib-core/src/main/java/com/google/blockly/android/ui/TrashCanView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldCheckboxView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldDateView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldDropdownView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldInputView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldLabelView.java
In order to support features such as tinting, the appcompat library will automatically load special appcompat replacements for the builtin widgets. However, this does not work for your own custom views.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/700)
> Fix CheckStyle AppCompat views.

- blocklylib-core/src/main/java/com/google/blockly/model/FieldDate.java
Almost all callers should use getDateInstance(), getDateTimeInstance(), or getTimeInstance() to get a ready-made instance of SimpleDateFormat suitable for the user's locale. The main reason you'd create an instance this class directly is because you need to format/parse a specific machine-readable format, in which case you almost certainly want to explicitly ask for US to ensure that you get ASCII digits (rather than, say, Arabic digits).
Here, we're parsing to/from a save file, therefore should be using US Locale for storing dates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/702)
> Fix Checkstyle DateFormat Locale

- blocklylib-core/src/main/java/com/google/blockly/android/ui/Rotation.java
When defining multiple constants for use in flags, the recommended style is to use the form 1 << 2, 1 << 3, 1 << 4 and so on to ensure that the constants are unique and non-overlapping.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/703)
> Fix rotation flag constant declaration

- blocklylib-core/src/main/res/layout/if_else_mutator_dialog.xml
When only a single widget in a LinearLayout defines a weight, it is more efficient to assign a width/height of 0dp to it since it will absorb all the remaining space anyway. With a declared width/height of 0dp it does not have to measure its own size first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/706)
> Fix inefficient layout weight

- blocklydemo/src/main/java/com/google/blockly/android/demo/FlyoutDemos.java
RecyclerView will not call onBindViewHolder again when the position of the item changes in the data set unless the item itself is invalidated or the new position cannot be determined.
For this reason, you should only use the position parameter while acquiring the related data item inside this method, and should not keep a copy of it.
If you need the position of an item later on (e.g. in a click listener), use getAdapterPosition() which will have the updated adapter position.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/707)
> Fix RecyclerView issue

- blocklylib-core/src/main/java/com/google/blockly/android/ui/Rotation.java
The change in the numbers caused some issue I haven't fully tracked down, but the change is definitely the cause of #715.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/716)
> Reverting PR #703, which caused #715

- blocklylib-core/src/main/java/com/google/blockly/utils/ColorUtils.java
Reverting DEFAULT_BLOCK_VALUE and DEFAULT_BLOCK_SATURATION (previously modified in #696).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/718)
> Fix solution in PR696.

- blocklydemo/build.gradle
- blocklylib-core/build.gradle
- blocklylib-vertical/build.gradle
- blocklytest/build.gradle
- build.gradle
Gradle is now `3.1.2`.
Build tools are now `27.0.3`.
Support libraries are now `27.1.1`.
All uses of `compile` have been replaced with either `implementation` or `api`. See [here](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration#new_configurations).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/724)
> Updating Gradle, build tools, dependencies, and dependency modes

- blocklydemo/build.gradle
- blocklylib-vertical/build.gradle
- deploy.properties
Updating version to `0.9-beta.20180725`, in preparation for new master release.
In attempt to temporarily resolve #736, this upcoming release reverts [one line gradle dependency](https://github.com/google/blockly-android/commit/11c56d2b5e041ec48b5bd025dce86a5f462ec05c#diff-a27c614c674557b911079935e04aaea5R27) change in #724.
Reverting back to a `compile` mode dependency introduces a warning message, and will fail in some future release shortly after the end of 2018.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/737)
> Version update: Partial rollback of gradle "api" usage

- blocklylib-core/src/main/res/layout/if_else_mutator_dialog.xml
- blocklylib-core/src/main/res/layout/procedure_definition_mutator_dialog.xml
_Fixes #734_
_This adds padding using android's ```?dialogPreferredPadding``` so it doesn't use any magic numbers and it fits with the dialog's style, I didn't do anything for top and bottom because I couldn't find any concrete numbers._
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/738)
> Add Padding To If/Else Mutator Dialog

- blocklylib-core/src/main/java/com/google/blockly/android/ui/CategoryTabs.java
Fixes #743. 
Tested via the DevTestsActivity, which has categories without color, and previous crashed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/744)
> Clear category tab tint if category color is null.

- blocklydemo/src/main/assets/sample_sections/mock_block_definitions.json
Black silhouette images were not showing on the block's default black background.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/745)
> Set block color for image test blocks.

- blocklylib-core/src/main/assets/default/text_blocks.json
The Blockly Web generators generate code for this as if it is a output block, but it's definition is that of a statement block, this generates incorrect code. This PR turns it into a output bock.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/760)
> Fix Prompt Block

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/model/Connection.java
modify: some code in BlocklyController.java & Connection.java
When the building block is replaced, it will be judged. If the newly generated connection is not empty and contains only one connectable input parameter, then the original intention is to connect the replaced building block to the new building block. However, there is no judgment on the type. If the type of the replaced block does not match the type required, the application will crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/755)
> fix: App crashed when replacing different types of blocks in input_connection

- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockRecyclerViewHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/CategoryTabs.java
- blocklylib-core/src/main/res/layout/default_flyout_bottom.xml
This automatically calculates a minimum height instead of hard coding it.
It also fixes a bug where if you scrolled the category tabs, and selected one, the old one would still look like it was selected when you scrolled back to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/771)
> Smarter Solution to #739
