google/blockly-android

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/311)
> Updating gradle.

- blocklylib-core/src/main/java/com/google/blockly/model/FieldNumber.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldNumberTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/330)
> Fix #329 Update FieldNumber to use inf or nan to mean no constraint

- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
Was familiarizing myself with the codebase when I encountered this annotation issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/331)
> Removed @NotNull annotation from a void method.

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/ConnectionManager.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/Dragger.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/DraggerTest.java
Moved bump methods from Dragger to Controller. Also moving more logic into .connect(..) call, in prep for events. It now takes one less parameter and includes call to bumpNeighbors(), which now include requestLayout().
Resolves #82.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/337)
> Moved bump methods from Dragger to Controller.

- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/LogAllEventsCallback.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyEvent.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/339)
> Adding new events, and a few tests to match.

- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/DeleteVariableDialog.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockFactoryTest.java
Some tweaks as a quick followup to adding variables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/344)
> Followup variable fixes

- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTestStrings.java
Fix #345
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/346)
> Don't allow shadow blocks to contain variables

- blocklylib-core/src/main/AndroidManifest.xml
- blocklytest/build.gradle
- blocklytest/src/androidTest/java/com/google/blockly/android/MockitoAndroidTestCase.java
- blocklytest/src/main/AndroidManifest.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/347)
> Updates to better support Espresso integration tests.

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
Numerous small event corrections and clean-up in BlocklyController. Partially addresses #342.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/349)
> BlocklyController clean up (partial)

- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/Dragger.java
- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
Should there be indications that immovable blocks are immovable?
I put the annotation in a separate commit in case you don't want to merge it (I'm not sure if it's idiomatic or not).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/332)
> Immovable block support

- blocklylib-core/src/main/assets/background_compiler.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/359)
> Print stack trace if generator fails.

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
@RoboErikG
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/358)
> Updating Gradle to 2.1.3

- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/ToolboxFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/TrashFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/ItemSpacingDecoration.java
- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/363)
> Enabling lint tests.  Fixing a few along the way.

- blocklydemo/src/main/assets/turtle/turtle.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/372)
> evironment -> environment

- blocklylib-core/src/main/assets/default/logic_blocks.json
- blocklylib-core/src/main/assets/default/loop_blocks.json
- blocklylib-core/src/main/assets/default/math_blocks.json
- blocklylib-core/src/main/assets/default/toolbox.xml
All blocks and all drop down fields have been tested for proper code generation through the Simple demo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/377)
> Adding new blocks: null, ternary, break/continue, and math properties.

- blocklylib-core/src/main/assets/default/colour_blocks.json
- blocklylib-core/src/main/assets/default/text_blocks.json
- blocklylib-core/src/main/assets/default/toolbox.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/395)
> colour_*, text_* blocks except text_join (mutator)

- blocklydemo/src/main/assets/turtle/toolbox_advanced.xml
- blocklydemo/src/main/assets/turtle/turtle_blocks.json
- blocklydemo/src/main/java/com/google/blockly/android/demo/TurtleActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/398)
> Adding new blocks to the Tutle demo.

- blocklydemo/src/main/java/com/google/blockly/android/demo/SimpleActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/406)
> Everything else that was supposed to be in #404.

- blocklylib-core/src/main/java/com/google/blockly/android/ui/VirtualWorkspaceView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/WorkspaceView.java
…but still constrain to the workspace.
Fixes #264.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/409)
> Fix scrolling to allow larger margins when blocks are smaller

- blocklylib-core/src/main/java/com/google/blockly/android/WorkspaceFragment.java
Accidental copy pasta.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/421)
> Fixing error in #416

- blocklylib-core/src/main/AndroidManifest.xml
- blocklylib-core/src/main/res/layout/drawers_and_action_bar.xml
- blocklylib-vertical/src/main/AndroidManifest.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/424)
> Minor fixes noted when exploring LTR issues.

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/430)
> Android tools version.

- blocklylib-core/src/main/java/com/google/blockly/android/codegen/CodeGeneratorService.java
- blocklylib-core/src/main/res/raw/test_blocks.json
- blocklytest/src/androidTest/java/com/google/blockly/android/codegen/CodeGeneratorServiceTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockFactoryTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTest.java
Includes tests at both the level of field serialization and JavaScript command creation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/436)
> Fixed JavaScript escaping of single quotes in fields.

- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldImageView.java
is there any way to load local asset in image field?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/442)
> local asset loading in image field

- blocklydemo/src/main/java/com/google/blockly/util/JavascriptUtil.java
Should cover #17.
Would it be useful to correctly escape unicode characters as well?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/454)
> Updated JavaScript string escaping (#17)

- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
Should cover #128.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/455)
> Removed BlocklyController.Builder asset manager (#128)

- blocklydemo/src/main/java/com/google/blockly/util/JavascriptUtil.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/456)
> JavascriptUtil: Limit use of forward slash escape. And adding comments.

- blocklydemo/src/main/java/com/google/blockly/util/JavascriptUtil.java
http://javajee.com/unicode-escapes-in-java <sigh>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/458)
> Escape my escape before I escape.

- blocklylib-core/src/main/java/com/google/blockly/android/ui/AbstractBlockView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/Dragger.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/PendingDrag.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/VirtualWorkspaceView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/461)
> #36 Remove use of MotionEventCompat

- blocklytest/src/androidTest/java/com/google/blockly/android/control/ProcedureManagerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldDropdownTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldNumberTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/462)
> #68 Use ExpectedException from JUnit 4 in Tests

- blocklytest/src/androidTest/java/com/google/blockly/utils/MoreAsserts.java
Minor change to tidy up some assertions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/463)
> Tidy up Assert.fail to use standard assertions.

- blocklytest/src/androidTest/java/com/google/blockly/android/codegen/CodeGeneratorServiceTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/AbstractBlockViewTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/AbstractInputViewTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/BlockGroupTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/BlockViewInActivityTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/DraggerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/WorkspaceHelperTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/vertical/VerticalBlockViewFactoryTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockFactoryTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlocklyEventTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/WorkspaceTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/467)
> Correct all references to R.raw.test_blocks to use the updated resource location.

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/NameVariableDialog.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/VariableChangeView.java
- blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java
- blocklytest/src/androidTest/java/com/google/blockly/android/BlocklyTestCase.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/WorkspaceStatsTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/WorkspaceHelperTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/ConnectionTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldAngleTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldCheckboxTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldColorTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldDateTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldImageTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldInputTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldLabelTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldVariableTest.java
- blocklytest/src/androidTest/java/com/google/blockly/utils/MoreAsserts.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/471)
> Removing unused imports.

- blocklytest/src/androidTest/java/com/google/blockly/android/control/ProcedureManagerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/WorkspaceStatsTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/472)
> Removing wildcard imports.

- blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/NameManagerTest.java
Fixes #470
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/475)
> Variable case sensitivity

- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/ToolboxFragment.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ToolboxFragentTest.java
Fixes #302
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/480)
> Close trash on toolbox open

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/482)
> Updating to the latest API, tools, and library versions.

- blocklylib-core/src/main/java/com/google/blockly/android/ui/WorkspaceHelper.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/483)
> Fix getViewableWorkspaceBounds()

- blocklydemo/build.gradle
- blocklylib-core/build.gradle
- blocklylib-vertical/build.gradle
- blocklytest/build.gradle
This is what #482 was supposed to be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/485)
> Updating gradle files with the latest API, tools, and library versions.

- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyEvent.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/ConnectionManager.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/Dragger.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/WorkspaceHelper.java
- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java
- blocklylib-core/src/main/java/com/google/blockly/model/Connection.java
- blocklylib-core/src/main/java/com/google/blockly/model/WorkspacePoint.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/ConnectionManagerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTestStrings.java
...and other related changes to specify positions on the workspace in floating point.
Pulls in #481 with additional corrections.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/487)
> Update WorkspacePoint to expend PointF instead of Point

- blocklydemo/src/main/assets/simple_playground_toolbox.xml
- blocklydemo/src/main/assets/turtle/toolbox_advanced.xml
- blocklylib-core/src/main/assets/default/logic_blocks.json
- blocklylib-core/src/main/assets/default/toolbox.xml
Fixes #413.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/494)
> Adding controls_ifelse block

- blocklytest/src/androidTest/java/com/google/blockly/android/ui/OnDragToTrashListenerTest.java
Was supposed to part of #490
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/495)
> Fixing test on OnDragToTrashListener.

- blocklylib-core/src/main/java/com/google/blockly/android/ToolboxFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/clipboard/BlockClipDataHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/clipboard/SingleMimeTypeClipDataHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/PendingDrag.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldInputView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldNumberView.java
- blocklylib-core/src/main/java/com/google/blockly/model/Connection.java
- blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ToolboxFragentTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/AbstractBlockViewTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/fieldview/BasicFieldCheckboxViewTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/fieldview/BasicFieldDropdownViewTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/fieldview/BasicFieldImageViewTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/fieldview/BasicFieldLabelViewTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/fieldview/BasicFieldVariableViewTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/vertical/VerticalBlockViewFactoryTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/496)
> Removing unused imports and code.

- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/codegen/CodeGeneratorManager.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/502)
> Move workspace serialization error handling into CodeGeneratorManager.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/506)
> Updating README with link to forum.

- blocklylib-core/src/main/java/com/google/blockly/android/ui/AbstractBlockView.java
- blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/BlockView.java
- blocklytest/src/androidTest/java/com/google/blockly/android/ui/AbstractBlockViewTest.java
Fixes #143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/505)
> Move common hitTest() logic into AbstractBlockView.

- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/StylesActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/508)
> Removing unused methods getStartingWorkspacePath() and getStyleResId()

- blocklydemo/src/main/java/com/google/blockly/android/demo/AlwaysOpenToolboxActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/SplitActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/TurtleActivity.java
- blocklydemo/src/main/res/layout/always_open_toolbox.xml
- blocklydemo/src/main/res/layout/styled_content.xml
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/BlocklyActivityHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/DefaultVariableCallback.java
- blocklylib-core/src/main/java/com/google/blockly/android/codegen/CodeGeneratorManager.java
- blocklylib-core/src/main/res/layout/blockly_unified_workspace.xml
- blocklytest/src/androidTest/java/com/google/blockly/android/BlocklyTestActivity.java
Extracting several Blockly initialization methods out of AbstractBlocklyActivity and into BlocklyActivityHelper, to make it easier to add Blockly to other Activity classes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/511)
> Adding BlocklyActivityHelper.

- blocklydemo/src/main/java/com/google/blockly/android/demo/StylesActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/BlockListUI.java
- blocklylib-core/src/main/java/com/google/blockly/android/CategorySelectorUI.java
- blocklylib-core/src/main/java/com/google/blockly/android/codegen/CodeGeneratorManager.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyEvent.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockRecyclerViewHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/CategoryView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/DeleteVariableDialog.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/NameVariableDialog.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/PendingDrag.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/TrashCanView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/VariableRequestCallback.java
- blocklylib-core/src/main/java/com/google/blockly/model/FlyoutCategory.java
- blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java
- blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/BlockView.java
- blocklytest/src/androidTest/java/com/google/blockly/android/FlyoutControllerTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/516)
> Adding copyright text. Removing unused imports.

- blocklylib-core/src/main/java/com/google/blockly/android/BlocklyActivityHelper.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/519)
> Use interfaces instead of FlyoutFragment

- blocklydemo/src/main/assets/sample_sections/level_2/toolbox.xml
- blocklydemo/src/main/assets/sample_sections/level_3/toolbox.xml
- blocklydemo/src/main/assets/turtle/toolbox_advanced.xml
- blocklylib-core/src/main/java/com/google/blockly/android/CategorySelectorFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/FlyoutFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/FlyoutController.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/VariableCategory.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockListUI.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockRecyclerViewHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/CategorySelectorUI.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/CategoryTabs.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/CategoryView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/FlyoutCallback.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlocklyCategory.java
- blocklylib-core/src/main/java/com/google/blockly/model/CategoryFactory.java
- blocklylib-core/src/main/java/com/google/blockly/model/FlyoutCategory.java
- blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java
- blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java
- blocklylib-core/src/main/res/layout/blockly_unified_workspace.xml
- blocklylib-core/src/main/res/layout/default_flyout_bottom.xml
- blocklylib-core/src/main/res/layout/default_flyout_start.xml
- blocklylib-core/src/main/res/layout/simple_button.xml
- blocklylib-core/src/main/res/layout/simple_label.xml
- blocklytest/src/androidTest/java/com/google/blockly/android/FlyoutControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
This adds support for labels and buttons to the flyouts and sets up a
way to create custom categories. It also adds a custom category for
variables that dynamically builds the blocks for the variables
category.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/523)
> Support custom categories and add VariablesCategory

- blocklydemo/src/main/java/com/google/blockly/android/demo/LogAllEventsCallback.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlocklyEvent.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldImage.java
- blocklylib-core/src/main/java/com/google/blockly/model/FieldNumber.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/BlocklyEventTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/522)
> Moving .android.control.BlocklyEvent to .mode.BlocklyEvent

- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/526)
> Removing unused category field in Block class

- blocklydemo/src/main/java/com/google/blockly/android/demo/SimpleActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/SplitActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/StylesActivity.java
- blocklylib-core/src/main/assets/default/toolbox.xml
- blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java
- blocklylib-core/src/main/java/com/google/blockly/model/VariableCategoryFactory.java
Variables no longer need to be initialized in the activity. Remove the inits from demos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/539)
> Remove variable init from demos

- blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlockTemplate.java
- blocklylib-core/src/main/java/com/google/blockly/model/VariableCategoryFactory.java
- blocklytest/src/androidTest/java/com/google/blockly/android/TestUtils.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/543)
> Throw BlockLoadingException on bad JSON definitions.

- blocklydemo/build.gradle
- blocklylib-core/build.gradle
- blocklylib-vertical/build.gradle
- blocklytest/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/547)
> Update build tools to latest version

- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockViewFactory.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldAngleView.java
- blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/VerticalBlockViewFactory.java
Fix code style issues: whitespace, method order.
Replace WorkspaceHelper with ViewCompat.getLayoutDirection().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/550)
> Fix minor issues in #453

- blocklylib-core/src/main/java/com/google/blockly/android/WorkspaceFragment.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/559)
> Default showing the grid to true

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/560)
> Update gradle build tools to 2.3.1

- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/562)
> Adding Block.setMutator()

- blocklydemo/src/main/assets/turtle/demo_workspaces/lacey_curves.xml
Aesthetic alignment:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/564)
> Aesthetic alignment.

- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockRecyclerViewHelper.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlocklyCategory.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/571)
> Fix crash when dragging from trash

- blocklylib-core/src/main/assets/default/math_blocks.json
- blocklylib-core/src/main/java/com/google/blockly/model/BlocklyEvent.java
- blocklylib-core/src/main/java/com/google/blockly/model/Connection.java
- blocklylib-core/src/main/java/com/google/blockly/model/DefaultBlocks.java
- blocklylib-core/src/main/java/com/google/blockly/model/Input.java
- blocklylib-core/src/main/java/com/google/blockly/model/mutator/MathIsDivisibleByMutator.java
- blocklytest/src/androidTest/java/com/google/blockly/model/mutator/MathIsDivisibleByMutatorTest.java
Does not include the BlockView support for the shape change (yet).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/575)
> Adding MathIsDivisibleByMutator for the "math_number_property" block.

- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklylib-core/src/main/java/com/google/blockly/model/mutator/MathIsDivisibleByMutator.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/576)
> Adding convenience form of Block.reshape(..)

- blocklydemo/build.gradle
- blocklylib-core/build.gradle
- blocklylib-vertical/build.gradle
- blocklytest/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/579)
> Set minimum 18, at least until #537 can be resolved.

- blocklylib-core/src/main/assets/default/toolbox.xml
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/BlocklyActivityHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java
- blocklylib-core/src/main/java/com/google/blockly/android/control/FlyoutController.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlocklyCategory.java
- blocklylib-core/src/main/java/com/google/blockly/model/DefaultBlocks.java
- blocklylib-core/src/main/java/com/google/blockly/model/FunctionCategoryFactory.java
- blocklylib-core/src/main/java/com/google/blockly/model/VariableCategoryFactory.java
- blocklytest/src/androidTest/java/com/google/blockly/android/FlyoutControllerTest.java
Also, refactored how custom categories are added, making it consistent with how activities (and the activity helper) add mutators and extensions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/590)
> Adding FunctionCategoryFactory to handle the custom PROCEDURE toolbox category.

- blocklylib-core/src/main/java/com/google/blockly/model/Block.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlocklyCategory.java
- blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java
- blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java
- blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java
- blocklytest/src/androidTest/java/com/google/blockly/model/WorkspaceTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/578)
> Fixes #567 set and unset workspaceId

- blocklytest/src/androidTest/java/com/google/blockly/model/WorkspaceTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/596)
> Removing unused import.

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/597)
> build:gradle:2.3.1 => build:gradle:2.3.2

- blocklylib-core/src/main/java/com/google/blockly/model/mutator/IfElseMutator.java
- blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java
Also adding some methods to BlocklyXmlHelper supporting writing XML that is not a block.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/598)
> Refactor IfElseMutator.update(..) to route through Block.setMutation().

- README.md
Update the registration link to one we can redirect if we change the form in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/599)
> Registration redirect link

- blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java
Fixes #609
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/610)
> Fix crash bug in getOrCreateVariableIndex

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/616)
> gradle 2.3.3

- blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java
Off by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/617)
> Compile time option to log the workspace XML string or stream

- blocklylib-core/src/main/java/com/google/blockly/android/ui/mutator/IfElseMutatorFragment.java
- blocklylib-core/src/main/java/com/google/blockly/model/mutator/IfElseMutator.java
- blocklylib-core/src/main/res/layout/if_else_mutator_dialog.xml
- blocklylib-core/src/main/res/values/strings.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/619)
> Correct additional conditional inputs to read "else if"

- blocklylib-core/src/main/java/com/google/blockly/model/DefaultBlocks.java
- blocklylib-core/src/main/java/com/google/blockly/model/ProcedureCustomCategory.java
Also fix if_return block.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/620)
> ProcedureCustomCategory: Reuse blocks when rebuilding category

- blocklylib-core/src/main/java/com/google/blockly/android/codegen/LanguageDefinition.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlocklyCategory.java
Moving TODOs out of the doc comments, per note in cl/163080836.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/636)
> Fixing TODOs in comments

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/637)
> Fix broken CONTRIBUTING link

- deploy.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/643)
> Correcting deployment version

- deploy.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/644)
> Merge master @ ac52ac8 onto develop

- blocklydemo/build.gradle
- blocklylib-core/build.gradle
- blocklylib-vertical/build.gradle
- blocklytest/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/650)
> Updating to Android support libraries 26.0.2

- blocklydemo/src/main/AndroidManifest.xml
- blocklydemo/src/main/java/com/google/blockly/android/demo/LuaActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/SimpleActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/SimpleFragment.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/SimpleFragmentHostActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/SplitActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/StylesActivity.java
- blocklydemo/src/main/java/com/google/blockly/android/demo/TurtleActivity.java
- blocklydemo/src/main/res/layout/simple_fragment.xml
- blocklydemo/src/main/res/values/strings.xml
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/BlocklyActivityHelper.java
- blocklytest/src/androidTest/java/com/google/blockly/android/BlocklyTestActivity.java
Also clarifying comments about the save path overrides.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/647)
> Adding AbstractBlocklyFragment and demo SimpleFragment

- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldNumberView.java
Fixes #661.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/662)
> Verify FieldNumber minimum is not NaN before comparing to zero.

- deploy.properties
0.9-beta.20171002
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/664)
> Updating version on master

- deploy.properties
... before pushing to master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/673)
> Updating version to 0.9-beta.20171003

- blocklylib-core/src/main/java/com/google/blockly/android/WorkspaceFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/VirtualWorkspaceView.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/WorkspaceGridRenderer.java
- blocklylib-core/src/main/res/values/attrs.xml
gridColor, gridSpacing and gridDotColor can all be set as attributes on a WorkspaceFragment.
(I haven't added backgroundColor, but it should be reasonably straightforward from here if someone else wants to pick that up).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/680)
>  #675 Allow gridColor, gridSpacing and gridDotColor

- .travis.yml
- blocklydemo/build.gradle
- blocklylib-core/build.gradle
- blocklylib-vertical/build.gradle
- blocklytest/build.gradle
- blocklytest/src/androidTest/java/com/google/blockly/model/BlockFactoryTest.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Updates gradle to 4.1, Android build tools to 3.0, and build API to 27.
Had to remove code testing logging because LogLogcatRule was removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/685)
> Updating project to Android Studio 3.0 release tools.

- blocklylib-core/src/main/assets/default/list_blocks.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/690)
> Input on block was not named correctly. Fixes #630.

- blocklylib-core/src/main/java/com/google/blockly/android/ui/Dragger.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/694)
> Correcting for whitespace style.

- blocklylib-core/src/main/java/com/google/blockly/utils/ColorUtils.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/696)
> 688 Make default block colour black.

- .travis.yml
- build.gradle
Fixes #625.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/697)
> 625 Add checkstyle and run it from travis

- blocklylib-core/src/main/java/com/google/blockly/model/BlockTemplate.java
Also replace assert with normal if check (always check this).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/704)
> Fixed argument assertion. FieldValue can be empty.

- blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldAngleView.java
- blocklylib-core/src/main/java/com/google/blockly/model/BlockTemplate.java
Assertions are unreliable in Dalvik and unimplemented in ART. Use BuildConfig.DEBUG conditional checks instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/699)
> Fix assertion Checkstyle warnings in core

- blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/WorkspaceHelper.java
See #701 and #705 for discussions on why these can be suppressed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/709)
> SuppressLint for issues that are known to be ok.

- blocklylib-core/src/main/java/com/google/blockly/android/WorkspaceFragment.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/WorkspaceGridRenderer.java
- blocklylib-core/src/main/res/values/attrs.xml
Fixes #675
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/710)
> Add backgroundColor attribute to WorkspaceFragment

- blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/711)
> #632 Fix {@link ActionBar} references

- blocklylib-core/src/main/java/com/google/blockly/model/FieldNumber.java
- blocklytest/src/androidTest/java/com/google/blockly/model/FieldNumberTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/712)
> #334 - Align FieldNumber constructor with main blockly APIs

- .travis.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/714)
> Updating Gradle tools to 3.0.1

- deploy.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/725)
> Updating version id to 0.9-beta.20180427

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/730)
> Upgrading to latest gradle v3.1.3

- deploy.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/732)
> Bumping version to 0.9-beta.20180709

- build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/742)
> Upgrading gradle to 3.1.4

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/747)
> Add deprecation notice / ceasing active development

- blocklylib-core/src/main/java/com/google/blockly/android/ui/BlockRecyclerViewHelper.java
- blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldVariableView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/774)
> Fixes #772, #773

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Gradle 4.10.1
Android Tools 3.3.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/blockly-android/775)
> Upgrade gradle, android tools
